#READ BEFORE RUNNING !!!

#These models will take a while to run and will save model outputs to the current directory
#For convenience, the model outputs are already saved to load and analyze so you don't have to run them from scratch
#All models generated by this script are in the BayesianRTRegressions folder
#Models are loaded and analyzed in the analyze bayesian RTregressions script

#this script is mainly provided for examination of data preprocessing and the code used to generate models
#it is not recommended you try to run this whole script for reasons noted above

####read in raw data files####
setwd("../rawdata/")
files = list.files(pattern = "*.txt")
for(file in files){
  thisdf<-read.table(file, header = T)
  if (file == files[1]){
    fulldf<-thisdf
  }
  else{
    fulldf<-rbind(thisdf, fulldf)
  }
}
setwd("..")



####preproc/data cleaning####
voldf<-subset(fulldf, task_cue == "?")
expdf<-subset(fulldf, task_cue != "?")

#set switches correctly for voldf
library(data.table)
voldf$sr[voldf$task != shift(voldf$task)]<-1
voldf$sr[voldf$task == shift(voldf$task)]<-0
voldf$sr[voldf$altRep == -1]<- -1

#remove subjects with bad switch rats from voldf
srtots<-aggregate(sr ~ subj, data = subset(voldf, altRep > -1), FUN = mean)
badsubs<-srtots$subj[srtots$sr > .8 | srtots$sr < .2]

voldf<-subset(voldf, !(subj %in% badsubs))

#remove bad accuracies from both
acctots_exp<-aggregate(task_acc ~ subj, data = expdf, FUN = mean)
badsubs<-acctots_exp$subj[acctots_exp$acc < .6]
expdf<-subset(expdf, !(subj %in% badsubs))

acctots_vol<-aggregate(task_acc ~ subj, data = voldf, FUN = mean)
badsubs<-acctots_vol$subj[acctots_vol$acc < .6]
voldf<-subset(voldf, !(subj %in% badsubs))

voldf$altRep<-voldf$sr
voldf$subj<-as.factor(voldf$subj)
expdf$subj<-as.factor(expdf$subj)
voldf$altRep<-as.factor(voldf$altRep)
expdf$altRep<-as.factor(expdf$altRep)
voldf$CSI<-as.factor(voldf$CSI)
expdf$CSI<-as.factor(expdf$CSI)
voldf$RSI<-as.factor(voldf$RSI)
expdf$RSI<-as.factor(expdf$RSI)

###
voldf<-subset(voldf, altRep != "-1")
expdf<-subset(expdf, altRep != "-1")

voldf<-subset(voldf, E1 < 1)
expdf<-subset(expdf, E1 < 1)

voldf<-subset(voldf, taskRT < (mean(taskRT) + 3*sd(taskRT)))
expdf<-subset(expdf, taskRT < (mean(taskRT) + 3*sd(taskRT)))

voldf<-subset(voldf, taskRT > 200)
expdf<-subset(expdf, taskRT > 200)

voldf$logRT<-log(voldf$taskRT)
expdf$logRT<-log(expdf$taskRT)

####brms tests of log RT, voluntary####
library(brms)


volB<-brm(logRT ~ altRep*CSI*RSI + (1 + altRep*CSI*RSI |subj),data = voldf)
summary(volB) #affected by both

volB2<-brm(logRT ~ altRep*CSI + altRep*RSI + (1 + altRep*CSI + altRep*RSI |subj),data = voldf)
summary(volB2) #affected by both
saveRDS(volB2, "voluntary-logRT-signinteractions-mod.rds")

volB3<-brm(logRT ~ CSI  + (1 + CSI | subj), data = subset(voldf, altRep == 1))
summary(volB3) #affected by both
saveRDS(volB3, "voluntary-logRT-CSISwitch-mod.rds")
marginal_effects(volB3)

volB4<-brm(logRT ~ RSI + (1 + RSI | subj), data = subset(voldf, altRep == 1))
summary(volB4) #affected by both
saveRDS(volB4, "voluntary-logRT-RSISwitch-mod.rds")
marginal_effects(volB4)

volB5<-brm(logRT ~ CSI + (1 + CSI | subj), data = subset(voldf, altRep == 0))
summary(volB5) #affected by both
saveRDS(volB5, "voluntary-logRT-CSIRepeat-mod.rds")
marginal_effects(volB5)

volB6<-brm(logRT ~ RSI + (1 + RSI | subj), data = subset(voldf, altRep == 0))
summary(volB6) #affected by both
saveRDS(volB6, "voluntary-logRT-RSIRepeat-mod.rds")
marginal_effects(volB6)

####brms tests of log RT, explicit####
expB<-brm(logRT ~ altRep*CSI*RSI + (1 + altRep*CSI*RSI |subj),data = expdf)
summary(expB) #three way interaction
saveRDS(expB, "explicit-logRT-allinteractions-mod.rds")

expB2<-brm(logRT ~ CSI*RSI + (1 + CSI*RSI |subj), data = subset(expdf, altRep == 1))
summary(expB2) #affected by both
saveRDS(expB2, "explicit-logRT-RSICSIinteraction-switch-mod.rds")

expB3<-brm(logRT ~ CSI*RSI + (1 + CSI*RSI |subj), data = subset(expdf, altRep == 0))
summary(expB3) #affected by both
saveRDS(expB3, "explicit-logRT-RSICSIinteraction-repeat-mod.rds")

expB4<-brm(logRT ~ RSI + (1 + RSI | subj), data = subset(expdf, altRep == 1))
saveRDS(expB4, "explicit-logRT-RSISwitch-mod.rds")
print(summary(expB4), digits=5)
marginal_effects(expB4)


expB5<-brm(logRT ~ CSI + (1 + CSI | subj), data = subset(expdf, altRep == 1))
saveRDS(expB5, "explicit-logRT-CSISwitch-mod.rds")
summary(expB5)
marginal_effects(expB5)

expB6<-brm(logRT ~ RSI + (1 + RSI | subj), data = subset(expdf, altRep == 0 & CSI == 100))
saveRDS(expB6, "explicit-logRT-RSIRepeat-shortCSI-mod.rds")
summary(expB6)
marginal_effects(expB6)

expB7<-brm(logRT ~ RSI + (1 + RSI | subj), data = subset(expdf, altRep == 0 & CSI == 1000))
saveRDS(expB7, "explicit-logRT-RSIRepeat-longCSI-mod.rds")
print(summary(expB7), digits=5)
marginal_effects(expB7)


expB8<-brm(logRT ~ CSI + (1 + CSI | subj), data = subset(expdf, altRep == 0 & RSI == 100))
saveRDS(expB8, "explicit-logRT-CSIRepeat-shortRSI-mod.rds")
print(summary(expB8), digits=5)
summary(expB8)


expB9<-brm(logRT ~ CSI + (1 + CSI | subj), data = subset(expdf, altRep == 0 & RSI == 1000))
saveRDS(expB9, "explicit-logRT-CSIRepeat-longRSI-mod.rds")
summary(expB9)
marginal_effects(expB9)
